# challenge Part 1, Get the Weather Description and amount of precipitation for each city.

In [1]:
!pip install citipy
from citipy import citipy
import numpy as np
import pandas as pd

Requirement already satisfied: citipy in /Users/jguo/opt/anaconda3/lib/python3.8/site-packages (0.0.5)
Requirement already satisfied: kdtree>=0.12 in /Users/jguo/opt/anaconda3/lib/python3.8/site-packages (from citipy) (0.16)

In [2]:
lats = np.random.uniform(low = -90.000, high = 90.000, size = 1500)
lngs = np.random.uniform(low = -180.000, high = 180.000, size = 1500)

lat_lngs = zip(lats,lngs)

In [3]:
# Add the latitude and longitude to a list

coordinates = list(lat_lngs)

In [4]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

616

In [5]:
#import the request library
import requests 

from datetime import datetime

from config import weather_api_key

In [6]:
url = f"http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID={weather_api_key}"

In [7]:
# List of city data

city_data = []

#print to logger
print("Beginning Data Retrieval")
print("-" * 25)

#Create a counter
record_count = 1
set_count = 1
for index, city in enumerate(cities):
    
    #Groups cities in sets of 50, for logging purpose
    if (index % 50 == 0 and index >= 50):
        set_count += 1
        record_count = 1
    #Create endpoint url with each city
    city_url = f'{url}&q={city.replace(" ", "+")}'
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    
    record_count +=1
    
    try:
        # Parse the JSON and retrieve data
        city_weather = requests.get(city_url).json()

        # Parse out the max temp, humidity, and cloudiness
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_weather_description = city_weather["weather"][0]["description"]
        
        try:
            city_rain_inches = city_weather["rain"]["1h"]
        except KeyError:
            city_rain_inches = 0
        try:
            city_snow_inches = city_weather["rain"]["1h"]
        except: KeyError
        city_snow_inches = 0

        # Append the City information into city_data list
        city_data.append(
            {
                "City": city,
                "Lat": city_lat,
                "Lng": city_lng,
                "Max Temp": city_max_temp,
                "Humidity": city_humidity,
                "Cloudiness": city_clouds,
                "Wind Speed": city_wind,
                "Country": city_country,
                "Current Description": city_weather_description,
                "Rain (inches)": city_rain_inches,
                "Snow (inches)": city_snow_inches,
                })

    # If an error is experienced, skip the city
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-------------------------
Processing Record 1 of Set 1 | korla
Processing Record 2 of Set 1 | jamestown
Processing Record 3 of Set 1 | airai
Processing Record 4 of Set 1 | tumannyy
City not found. Skipping...
Processing Record 5 of Set 1 | fort nelson
Processing Record 6 of Set 1 | victoria
Processing Record 7 of Set 1 | fayaoue
Processing Record 8 of Set 1 | sechura
Processing Record 9 of Set 1 | puerto ayora
Processing Record 10 of Set 1 | barrow
Processing Record 11 of Set 1 | panlaitan
Processing Record 12 of Set 1 | castro
Processing Record 13 of Set 1 | cape town
Processing Record 14 of Set 1 | port augusta
Processing Record 15 of Set 1 | punta arenas
Processing Record 16 of Set 1 | albany
Processing Record 17 of Set 1 | vaini
Processing Record 18 of Set 1 | new norfolk
Processing Record 19 of Set 1 | kokstad
Processing Record 20 of Set 1 | avarua
Processing Record 21 of Set 1 | san isidro
Processing Record 22 of Set 1 | acari
Processing Record 23 of Set 1 | busselton
Processing Record 24 of Set 1 | faanui
Processing Record 25 of Set 1 | gurgan
City not found. Skipping...
Processing Record 26 of Set 1 | komsomolskiy
Processing Record 27 of Set 1 | barentsburg
City not found. Skipping...
Processing Record 28 of Set 1 | kapaa
Processing Record 29 of Set 1 | taolanaro
City not found. Skipping...
Processing Record 30 of Set 1 | north bend
Processing Record 31 of Set 1 | catarama
Processing Record 32 of Set 1 | vestmanna
Processing Record 33 of Set 1 | yellowknife
Processing Record 34 of Set 1 | hobart
Processing Record 35 of Set 1 | sitka
Processing Record 36 of Set 1 | rikitea
Processing Record 37 of Set 1 | san rafael
Processing Record 38 of Set 1 | bubaque
Processing Record 39 of Set 1 | rudbar
Processing Record 40 of Set 1 | padang
Processing Record 41 of Set 1 | tautira
Processing Record 42 of Set 1 | lebu
Processing Record 43 of Set 1 | mikun
Processing Record 44 of Set 1 | moctezuma
Processing Record 45 of Set 1 | nikolskoye
Processing Record 46 of Set 1 | hermanus
Processing Record 47 of Set 1 | allen
Processing Record 48 of Set 1 | arraial do cabo
Processing Record 49 of Set 1 | touros
Processing Record 50 of Set 1 | port alfred
Processing Record 1 of Set 2 | bredasdorp
Processing Record 2 of Set 2 | kawana waters
City not found. Skipping...
Processing Record 3 of Set 2 | adre
Processing Record 4 of Set 2 | lompoc
Processing Record 5 of Set 2 | butaritari
Processing Record 6 of Set 2 | athens
Processing Record 7 of Set 2 | sistranda
Processing Record 8 of Set 2 | tasiilaq
Processing Record 9 of Set 2 | ushuaia
Processing Record 10 of Set 2 | rio brilhante
Processing Record 11 of Set 2 | nanortalik
Processing Record 12 of Set 2 | coahuayana
Processing Record 13 of Set 2 | saldanha
Processing Record 14 of Set 2 | kontagora
Processing Record 15 of Set 2 | margate
Processing Record 16 of Set 2 | gusev
Processing Record 17 of Set 2 | kendari
Processing Record 18 of Set 2 | bardiyah
Processing Record 19 of Set 2 | bluff
Processing Record 20 of Set 2 | araguacu
Processing Record 21 of Set 2 | riyadh
Processing Record 22 of Set 2 | torbay
Processing Record 23 of Set 2 | zhezkazgan
Processing Record 24 of Set 2 | atuona
Processing Record 25 of Set 2 | koslan
Processing Record 26 of Set 2 | saint-philippe
Processing Record 27 of Set 2 | port hedland
Processing Record 28 of Set 2 | dikson
Processing Record 29 of Set 2 | ribeira grande
Processing Record 30 of Set 2 | kloulklubed
Processing Record 31 of Set 2 | dunedin
Processing Record 32 of Set 2 | manaus
Processing Record 33 of Set 2 | vila franca do campo
Processing Record 34 of Set 2 | chokurdakh
Processing Record 35 of Set 2 | mataura
Processing Record 36 of Set 2 | christchurch
Processing Record 37 of Set 2 | mar del plata
Processing Record 38 of Set 2 | aswan
Processing Record 39 of Set 2 | aksarka
Processing Record 40 of Set 2 | ilulissat
Processing Record 41 of Set 2 | palabuhanratu
City not found. Skipping...
Processing Record 42 of Set 2 | praia da vitoria
Processing Record 43 of Set 2 | valdosta
Processing Record 44 of Set 2 | phan rang
City not found. Skipping...
Processing Record 45 of Set 2 | constitucion
Processing Record 46 of Set 2 | alta floresta
Processing Record 47 of Set 2 | bengkulu
Processing Record 48 of Set 2 | east london
Processing Record 49 of Set 2 | tsihombe
City not found. Skipping...
Processing Record 50 of Set 2 | karratha
Processing Record 1 of Set 3 | sofiysk
City not found. Skipping...
Processing Record 2 of Set 3 | sentyabrskiy
City not found. Skipping...
Processing Record 3 of Set 3 | carbonia
Processing Record 4 of Set 3 | pevek
Processing Record 5 of Set 3 | klaksvik
Processing Record 6 of Set 3 | pilar
Processing Record 7 of Set 3 | katima mulilo
Processing Record 8 of Set 3 | bethel
Processing Record 9 of Set 3 | abha
Processing Record 10 of Set 3 | kattivakkam
Processing Record 11 of Set 3 | baykit
Processing Record 12 of Set 3 | hithadhoo
Processing Record 13 of Set 3 | kruisfontein
Processing Record 14 of Set 3 | ahuimanu
Processing Record 15 of Set 3 | taoudenni
Processing Record 16 of Set 3 | pakxan
Processing Record 17 of Set 3 | totma
Processing Record 18 of Set 3 | axim
Processing Record 19 of Set 3 | carnarvon
Processing Record 20 of Set 3 | ust-omchug
Processing Record 21 of Set 3 | dukat
Processing Record 22 of Set 3 | lucapa
Processing Record 23 of Set 3 | magan
Processing Record 24 of Set 3 | khatanga
Processing Record 25 of Set 3 | channel-port aux basques
Processing Record 26 of Set 3 | srednekolymsk
Processing Record 27 of Set 3 | jacareacanga
Processing Record 28 of Set 3 | sao joao da barra
Processing Record 29 of Set 3 | thompson
Processing Record 30 of Set 3 | rungata
City not found. Skipping...
Processing Record 31 of Set 3 | george town
Processing Record 32 of Set 3 | severo-kurilsk
Processing Record 33 of Set 3 | finschhafen
Processing Record 34 of Set 3 | pahrump
Processing Record 35 of Set 3 | tiksi
Processing Record 36 of Set 3 | ruteng
Processing Record 37 of Set 3 | grand gaube
Processing Record 38 of Set 3 | deputatskiy
Processing Record 39 of Set 3 | haines junction
Processing Record 40 of Set 3 | ushibuka
Processing Record 41 of Set 3 | usinsk
Processing Record 42 of Set 3 | yarmouth
Processing Record 43 of Set 3 | cabo san lucas
Processing Record 44 of Set 3 | saint-augustin
Processing Record 45 of Set 3 | sorsk
Processing Record 46 of Set 3 | nha trang
Processing Record 47 of Set 3 | namibe
Processing Record 48 of Set 3 | bacolod
Processing Record 49 of Set 3 | kodiak
Processing Record 50 of Set 3 | upata
Processing Record 1 of Set 4 | port-cartier
Processing Record 2 of Set 4 | narwar
Processing Record 3 of Set 4 | zhuji
Processing Record 4 of Set 4 | hamilton
Processing Record 5 of Set 4 | markova
Processing Record 6 of Set 4 | bandarbeyla
Processing Record 7 of Set 4 | esperance
Processing Record 8 of Set 4 | luderitz
Processing Record 9 of Set 4 | saskylakh
Processing Record 10 of Set 4 | illoqqortoormiut
City not found. Skipping...
Processing Record 11 of Set 4 | barcelos
Processing Record 12 of Set 4 | hambantota
Processing Record 13 of Set 4 | port hawkesbury
Processing Record 14 of Set 4 | tori
Processing Record 15 of Set 4 | lahaina
Processing Record 16 of Set 4 | lahad datu
Processing Record 17 of Set 4 | kapit
Processing Record 18 of Set 4 | broken hill
Processing Record 19 of Set 4 | yagodnoye
Processing Record 20 of Set 4 | beringovskiy
Processing Record 21 of Set 4 | kaitangata
Processing Record 22 of Set 4 | tomatlan
Processing Record 23 of Set 4 | mayo
Processing Record 24 of Set 4 | abiy adi
City not found. Skipping...
Processing Record 25 of Set 4 | qaanaaq
Processing Record 26 of Set 4 | provideniya
Processing Record 27 of Set 4 | maues
Processing Record 28 of Set 4 | bamiantong
Processing Record 29 of Set 4 | nguiu
City not found. Skipping...
Processing Record 30 of Set 4 | bage
Processing Record 31 of Set 4 | chuy
Processing Record 32 of Set 4 | bunia
Processing Record 33 of Set 4 | belushya guba
City not found. Skipping...
Processing Record 34 of Set 4 | rindal
Processing Record 35 of Set 4 | akyab
Processing Record 36 of Set 4 | pacific grove
Processing Record 37 of Set 4 | port lincoln

Processing Record 38 of Set 4 | ban nahin
Processing Record 39 of Set 4 | walvis bay
Processing Record 40 of Set 4 | umzimvubu
City not found. Skipping...
Processing Record 41 of Set 4 | pisco
Processing Record 42 of Set 4 | kanniyakumari
Processing Record 43 of Set 4 | dingle
Processing Record 44 of Set 4 | igrim
Processing Record 45 of Set 4 | binga
Processing Record 46 of Set 4 | abapo
Processing Record 47 of Set 4 | leningradskiy
Processing Record 48 of Set 4 | batemans bay
Processing Record 49 of Set 4 | cidreira
Processing Record 50 of Set 4 | vardo
Processing Record 1 of Set 5 | samarai
Processing Record 2 of Set 5 | port hardy
Processing Record 3 of Set 5 | tilichiki
Processing Record 4 of Set 5 | hilo
Processing Record 5 of Set 5 | san patricio
Processing Record 6 of Set 5 | porto novo
Processing Record 7 of Set 5 | talnakh
Processing Record 8 of Set 5 | tuktoyaktuk
Processing Record 9 of Set 5 | llanelli
Processing Record 10 of Set 5 | abong mbang
Processing Record 11 of Set 5 | livingston
Processing Record 12 of Set 5 | phangnga
Processing Record 13 of Set 5 | port hueneme
Processing Record 14 of Set 5 | ampanihy
Processing Record 15 of Set 5 | dubna
Processing Record 16 of Set 5 | hasaki
Processing Record 17 of Set 5 | meulaboh
Processing Record 18 of Set 5 | ambon
Processing Record 19 of Set 5 | uspenka
Processing Record 20 of Set 5 | rawannawi
City not found. Skipping...
Processing Record 21 of Set 5 | huarmey
Processing Record 22 of Set 5 | concordia
Processing Record 23 of Set 5 | nizhneyansk
City not found. Skipping...
Processing Record 24 of Set 5 | norman wells
Processing Record 25 of Set 5 | alofi
Processing Record 26 of Set 5 | samusu
City not found. Skipping...
Processing Record 27 of Set 5 | fukuchiyama
Processing Record 28 of Set 5 | fernley
Processing Record 29 of Set 5 | nemuro
Processing Record 30 of Set 5 | naberera
Processing Record 31 of Set 5 | sabya
Processing Record 32 of Set 5 | marystown
Processing Record 33 of Set 5 | faya
Processing Record 34 of Set 5 | pangody
Processing Record 35 of Set 5 | boca do acre
Processing Record 36 of Set 5 | catamarca
Processing Record 37 of Set 5 | terra santa
Processing Record 38 of Set 5 | south lake tahoe
Processing Record 39 of Set 5 | tarudant
City not found. Skipping...
Processing Record 40 of Set 5 | clyde river
Processing Record 41 of Set 5 | pemangkat
Processing Record 42 of Set 5 | bajo baudo
City not found. Skipping...
Processing Record 43 of Set 5 | kamenskoye
City not found. Skipping...
Processing Record 44 of Set 5 | reitz
Processing Record 45 of Set 5 | arona
Processing Record 46 of Set 5 | muzhi
Processing Record 47 of Set 5 | high level
Processing Record 48 of Set 5 | esso
Processing Record 49 of Set 5 | kupang
Processing Record 50 of Set 5 | ye
City not found. Skipping...
Processing Record 1 of Set 6 | fortuna
Processing Record 2 of Set 6 | paragominas
Processing Record 3 of Set 6 | okhotsk
Processing Record 4 of Set 6 | rayachoti
Processing Record 5 of Set 6 | cururupu
Processing Record 6 of Set 6 | pierre
Processing Record 7 of Set 6 | cobija
Processing Record 8 of Set 6 | attawapiskat
City not found. Skipping...
Processing Record 9 of Set 6 | saint george
Processing Record 10 of Set 6 | ancud
Processing Record 11 of Set 6 | rincon
Processing Record 12 of Set 6 | nantucket
Processing Record 13 of Set 6 | chunoyar
Processing Record 14 of Set 6 | balabac
Processing Record 15 of Set 6 | charlestown
Processing Record 16 of Set 6 | cabot
Processing Record 17 of Set 6 | gorom-gorom
Processing Record 18 of Set 6 | carballo
Processing Record 19 of Set 6 | cozumel
Processing Record 20 of Set 6 | djambala
Processing Record 21 of Set 6 | hofn
Processing Record 22 of Set 6 | polovinnoye
Processing Record 23 of Set 6 | glace bay
Processing Record 24 of Set 6 | mahebourg
Processing Record 25 of Set 6 | dayong
Processing Record 26 of Set 6 | campana
Processing Record 27 of Set 6 | souillac
Processing Record 28 of Set 6 | los llanos de aridane
Processing Record 29 of Set 6 | onega
Processing Record 30 of Set 6 | zlobin
Processing Record 31 of Set 6 | jesus carranza
Processing Record 32 of Set 6 | maliig
Processing Record 33 of Set 6 | altay
Processing Record 34 of Set 6 | grindavik
Processing Record 35 of Set 6 | upernavik
Processing Record 36 of Set 6 | portland
Processing Record 37 of Set 6 | galle
Processing Record 38 of Set 6 | port elizabeth
Processing Record 39 of Set 6 | san cristobal
Processing Record 40 of Set 6 | ornskoldsvik
Processing Record 41 of Set 6 | san jose iturbide
Processing Record 42 of Set 6 | saryshagan
City not found. Skipping...
Processing Record 43 of Set 6 | cairns
Processing Record 44 of Set 6 | bonavista
Processing Record 45 of Set 6 | chivay
Processing Record 46 of Set 6 | lagoa
Processing Record 47 of Set 6 | taywarah
Processing Record 48 of Set 6 | ulaangom
Processing Record 49 of Set 6 | bambous virieux
Processing Record 50 of Set 6 | las animas
Processing Record 1 of Set 7 | solsvik
City not found. Skipping...
Processing Record 2 of Set 7 | bourail
Processing Record 3 of Set 7 | saurimo
Processing Record 4 of Set 7 | raudeberg
Processing Record 5 of Set 7 | wawa
Processing Record 6 of Set 7 | olafsvik
Processing Record 7 of Set 7 | mys shmidta
City not found. Skipping...
Processing Record 8 of Set 7 | laguna
Processing Record 9 of Set 7 | coro
Processing Record 10 of Set 7 | libourne
Processing Record 11 of Set 7 | normal
Processing Record 12 of Set 7 | ketchikan
Processing Record 13 of Set 7 | mocambique
City not found. Skipping...
Processing Record 14 of Set 7 | alyangula
Processing Record 15 of Set 7 | amderma
City not found. Skipping...
Processing Record 16 of Set 7 | lolua
City not found. Skipping...
Processing Record 17 of Set 7 | goedereede
Processing Record 18 of Set 7 | fare
Processing Record 19 of Set 7 | saint anthony
Processing Record 20 of Set 7 | havoysund
Processing Record 21 of Set 7 | katsuura
Processing Record 22 of Set 7 | banihal
Processing Record 23 of Set 7 | houlung
City not found. Skipping...
Processing Record 24 of Set 7 | balikpapan
Processing Record 25 of Set 7 | pangoa
Processing Record 26 of Set 7 | praia
Processing Record 27 of Set 7 | hargeysa
Processing Record 28 of Set 7 | sena madureira
Processing Record 29 of Set 7 | belmonte
Processing Record 30 of Set 7 | gangotri
City not found. Skipping...
Processing Record 31 of Set 7 | broome
Processing Record 32 of Set 7 | ponta do sol
Processing Record 33 of Set 7 | artyk
City not found. Skipping...
Processing Record 34 of Set 7 | porbandar
Processing Record 35 of Set 7 | nova prata
Processing Record 36 of Set 7 | quelimane
Processing Record 37 of Set 7 | ranong
Processing Record 38 of Set 7 | suoyarvi
Processing Record 39 of Set 7 | mbandaka
Processing Record 40 of Set 7 | ferme-neuve
Processing Record 41 of Set 7 | mgandu
Processing Record 42 of Set 7 | gazanjyk
Processing Record 43 of Set 7 | acapulco
Processing Record 44 of Set 7 | kahului
Processing Record 45 of Set 7 | zelenogradsk
Processing Record 46 of Set 7 | buinsk
Processing Record 47 of Set 7 | geraldton
Processing Record 48 of Set 7 | camacha
Processing Record 49 of Set 7 | belyy yar
Processing Record 50 of Set 7 | barra do garcas
Processing Record 1 of Set 8 | egvekinot
Processing Record 2 of Set 8 | warah
Processing Record 3 of Set 8 | kalabo
Processing Record 4 of Set 8 | sioux lookout
Processing Record 5 of Set 8 | general roca
Processing Record 6 of Set 8 | sawtell
Processing Record 7 of Set 8 | codrington
Processing Record 8 of Set 8 | mercedes
Processing Record 9 of Set 8 | manggar
Processing Record 10 of Set 8 | lavrentiya
Processing Record 11 of Set 8 | inongo
Processing Record 12 of Set 8 | hami
Processing Record 13 of Set 8 | vila velha
Processing Record 14 of Set 8 | idah
Processing Record 15 of Set 8 | alice springs
Processing Record 16 of Set 8 | manta
Processing Record 17 of Set 8 | skibbereen
Processing Record 18 of Set 8 | kerteh
City not found. Skipping...
Processing Record 19 of Set 8 | darhan
Processing Record 20 of Set 8 | mutsamudu
City not found. Skipping...
Processing Record 21 of Set 8 | terrace bay
Processing Record 22 of Set 8 | seoul
Processing Record 23 of Set 8 | pithoro

Processing Record 24 of Set 8 | svetlyy
Processing Record 25 of Set 8 | sain alto
Processing Record 26 of Set 8 | whitehorse
Processing Record 27 of Set 8 | ishigaki
Processing Record 28 of Set 8 | vila
Processing Record 29 of Set 8 | nicoya
Processing Record 30 of Set 8 | maiduguri
Processing Record 31 of Set 8 | mandalgovi
Processing Record 32 of Set 8 | ayabaca
Processing Record 33 of Set 8 | husavik
Processing Record 34 of Set 8 | maningrida
Processing Record 35 of Set 8 | sterlibashevo
Processing Record 36 of Set 8 | saint-louis
Processing Record 37 of Set 8 | moengo
Processing Record 38 of Set 8 | velyka oleksandrivka
Processing Record 39 of Set 8 | cayenne
Processing Record 40 of Set 8 | peterhead
Processing Record 41 of Set 8 | inhambane
Processing Record 42 of Set 8 | isangel
Processing Record 43 of Set 8 | narsaq
Processing Record 44 of Set 8 | upington
Processing Record 45 of Set 8 | kavieng
Processing Record 46 of Set 8 | dongfeng
Processing Record 47 of Set 8 | bud
Processing Record 48 of Set 8 | karoi
Processing Record 49 of Set 8 | grand river south east
City not found. Skipping...
Processing Record 50 of Set 8 | yarqa
Processing Record 1 of Set 9 | kokorevka
Processing Record 2 of Set 9 | malanje
Processing Record 3 of Set 9 | itupiranga
Processing Record 4 of Set 9 | ornes
Processing Record 5 of Set 9 | almeria
Processing Record 6 of Set 9 | smoky lake
Processing Record 7 of Set 9 | palmer
Processing Record 8 of Set 9 | hanna
Processing Record 9 of Set 9 | campbell river
Processing Record 10 of Set 9 | tuatapere
Processing Record 11 of Set 9 | katha
City not found. Skipping...
Processing Record 12 of Set 9 | makakilo city
Processing Record 13 of Set 9 | cockburn town
Processing Record 14 of Set 9 | westport
Processing Record 15 of Set 9 | namestovo
Processing Record 16 of Set 9 | toora-khem
Processing Record 17 of Set 9 | laukaa
Processing Record 18 of Set 9 | yuzha
Processing Record 19 of Set 9 | ust-kuyga
Processing Record 20 of Set 9 | iqaluit
Processing Record 21 of Set 9 | henties bay
Processing Record 22 of Set 9 | sao lourenco do oeste
Processing Record 23 of Set 9 | andilamena
Processing Record 24 of Set 9 | melo
Processing Record 25 of Set 9 | longyearbyen
Processing Record 26 of Set 9 | ravar
Processing Record 27 of Set 9 | am timan
Processing Record 28 of Set 9 | shu
Processing Record 29 of Set 9 | baymak
Processing Record 30 of Set 9 | manzanillo
Processing Record 31 of Set 9 | yuzhno-yeniseyskiy
City not found. Skipping...
Processing Record 32 of Set 9 | ahipara
Processing Record 33 of Set 9 | sambava
Processing Record 34 of Set 9 | nefteyugansk
Processing Record 35 of Set 9 | lapua
Processing Record 36 of Set 9 | anahuac
Processing Record 37 of Set 9 | puro
Processing Record 38 of Set 9 | olavarria
Processing Record 39 of Set 9 | botro
Processing Record 40 of Set 9 | ladushkin
Processing Record 41 of Set 9 | sungai padi
Processing Record 42 of Set 9 | sandwick
Processing Record 43 of Set 9 | mezhova
Processing Record 44 of Set 9 | lubbock
Processing Record 45 of Set 9 | rocha
Processing Record 46 of Set 9 | winslow
Processing Record 47 of Set 9 | yulara
Processing Record 48 of Set 9 | alotau
City not found. Skipping...
Processing Record 49 of Set 9 | samalaeulu
City not found. Skipping...
Processing Record 50 of Set 9 | rafraf
Processing Record 1 of Set 10 | gwanda
Processing Record 2 of Set 10 | coihaique
Processing Record 3 of Set 10 | eyemouth
Processing Record 4 of Set 10 | saint-francois
Processing Record 5 of Set 10 | gat
Processing Record 6 of Set 10 | ulstrup
Processing Record 7 of Set 10 | mujiayingzi
Processing Record 8 of Set 10 | harlingen
Processing Record 9 of Set 10 | ballina
Processing Record 10 of Set 10 | pontianak
Processing Record 11 of Set 10 | nkhata bay
Processing Record 12 of Set 10 | manado
Processing Record 13 of Set 10 | mrirt
City not found. Skipping...
Processing Record 14 of Set 10 | puerto escondido
Processing Record 15 of Set 10 | ixtapa
Processing Record 16 of Set 10 | ugoofaaru
Processing Record 17 of Set 10 | isla mujeres
Processing Record 18 of Set 10 | matara
Processing Record 19 of Set 10 | prince rupert
Processing Record 20 of Set 10 | elva
Processing Record 21 of Set 10 | saint-alexandre
Processing Record 22 of Set 10 | mubi
Processing Record 23 of Set 10 | mogadishu
Processing Record 24 of Set 10 | nanakuli
Processing Record 25 of Set 10 | lata
Processing Record 26 of Set 10 | aguimes
Processing Record 27 of Set 10 | gaoua
Processing Record 28 of Set 10 | kenora
Processing Record 29 of Set 10 | valparaiso
Processing Record 30 of Set 10 | kargasok
Processing Record 31 of Set 10 | mount isa
Processing Record 32 of Set 10 | tritenii de jos
Processing Record 33 of Set 10 | guerrero negro
Processing Record 34 of Set 10 | trofaiach
Processing Record 35 of Set 10 | slovenska bistrica
Processing Record 36 of Set 10 | mersing
Processing Record 37 of Set 10 | karlskrona
Processing Record 38 of Set 10 | zavetnoye
Processing Record 39 of Set 10 | flinders
Processing Record 40 of Set 10 | kirovsk
Processing Record 41 of Set 10 | blythe
Processing Record 42 of Set 10 | great bend
Processing Record 43 of Set 10 | meadow lake
Processing Record 44 of Set 10 | saint-donat-de-montcalm
Processing Record 45 of Set 10 | mastic beach
Processing Record 46 of Set 10 | cascais
Processing Record 47 of Set 10 | uthal
Processing Record 48 of Set 10 | gualeguay
Processing Record 49 of Set 10 | georgetown
Processing Record 50 of Set 10 | oranjemund
Processing Record 1 of Set 11 | waitara
Processing Record 2 of Set 11 | hualmay
Processing Record 3 of Set 11 | tigil
Processing Record 4 of Set 11 | nagram
Processing Record 5 of Set 11 | port-gentil
Processing Record 6 of Set 11 | yibin
Processing Record 7 of Set 11 | vostok
Processing Record 8 of Set 11 | musafirkhana
Processing Record 9 of Set 11 | coos bay
Processing Record 10 of Set 11 | romitan
Processing Record 11 of Set 11 | kodinsk
Processing Record 12 of Set 11 | acarau
Processing Record 13 of Set 11 | aasiaat
Processing Record 14 of Set 11 | anadyr
Processing Record 15 of Set 11 | saint stephen
Processing Record 16 of Set 11 | south river
Processing Record 17 of Set 11 | tromso
Processing Record 18 of Set 11 | rottingdean
Processing Record 19 of Set 11 | takoradi
Processing Record 20 of Set 11 | vestmannaeyjar
Processing Record 21 of Set 11 | bhuj
Processing Record 22 of Set 11 | kirkuk
Processing Record 23 of Set 11 | boguchany
Processing Record 24 of Set 11 | payson
Processing Record 25 of Set 11 | udachnyy
Processing Record 26 of Set 11 | basco
Processing Record 27 of Set 11 | zhetysay
Processing Record 28 of Set 11 | haikou
Processing Record 29 of Set 11 | kelso
Processing Record 30 of Set 11 | rusape
Processing Record 31 of Set 11 | wasilla
Processing Record 32 of Set 11 | puerto penasco
Processing Record 33 of Set 11 | ewa beach
Processing Record 34 of Set 11 | flin flon
Processing Record 35 of Set 11 | coquimbo
Processing Record 36 of Set 11 | bireun
Processing Record 37 of Set 11 | elblag
Processing Record 38 of Set 11 | atar
Processing Record 39 of Set 11 | pechenga
Processing Record 40 of Set 11 | kaluga
Processing Record 41 of Set 11 | avera
Processing Record 42 of Set 11 | skagen
Processing Record 43 of Set 11 | talaya
Processing Record 44 of Set 11 | chapais
Processing Record 45 of Set 11 | concarneau
Processing Record 46 of Set 11 | dongsheng
Processing Record 47 of Set 11 | indri
Processing Record 48 of Set 11 | imeni poliny osipenko
Processing Record 49 of Set 11 | bairiki
Processing Record 50 of Set 11 | hihifo
City not found. Skipping...
Processing Record 1 of Set 12 | porto walter
Processing Record 2 of Set 12 | pedernales
Processing Record 3 of Set 12 | nouadhibou
Processing Record 4 of Set 12 | borlange
City not found. Skipping...
Processing Record 5 of Set 12 | moyobamba
Processing Record 6 of Set 12 | iquique
Processing Record 7 of Set 12 | galdar
Processing Record 8 of Set 12 | chom bung
City not found. Skipping...
Processing Record 9 of Set 12 | shetpe
Processing Record 10 of Set 12 | kavaratti
Processing Record 11 of Set 12 | adrar
Processing Record 12 of Set 12 | nizhniy tsasuchey
Processing Record 13 of Set 12 | bodden town

Processing Record 14 of Set 12 | kimbe
Processing Record 15 of Set 12 | valencia
Processing Record 16 of Set 12 | aleksandrov gay
Processing Record 17 of Set 12 | gamboula
Processing Record 18 of Set 12 | nawada
Processing Record 19 of Set 12 | ayagoz
Processing Record 20 of Set 12 | agadez
Processing Record 21 of Set 12 | helong
Processing Record 22 of Set 12 | cherskiy
Processing Record 23 of Set 12 | bassano
Processing Record 24 of Set 12 | sahaswan
Processing Record 25 of Set 12 | kjollefjord
Processing Record 26 of Set 12 | isabela
Processing Record 27 of Set 12 | yantal
Processing Record 28 of Set 12 | jiangdu
Processing Record 29 of Set 12 | eureka
Processing Record 30 of Set 12 | ciudad ojeda
Processing Record 31 of Set 12 | oneonta
Processing Record 32 of Set 12 | strezhevoy
Processing Record 33 of Set 12 | ler
Processing Record 34 of Set 12 | gurskoye
City not found. Skipping...
Processing Record 35 of Set 12 | ayr
Processing Record 36 of Set 12 | abay
Processing Record 37 of Set 12 | cabedelo
Processing Record 38 of Set 12 | junin
Processing Record 39 of Set 12 | canaries
Processing Record 40 of Set 12 | cheney
Processing Record 41 of Set 12 | ossora
Processing Record 42 of Set 12 | ostrovnoy
Processing Record 43 of Set 12 | lusambo
Processing Record 44 of Set 12 | sheridan
Processing Record 45 of Set 12 | maromitsa
Processing Record 46 of Set 12 | miraflores
Processing Record 47 of Set 12 | tsaratanana
Processing Record 48 of Set 12 | gravdal
Processing Record 49 of Set 12 | marfino
Processing Record 50 of Set 12 | brae
Processing Record 1 of Set 13 | tazovskiy
Processing Record 2 of Set 13 | ortakoy
Processing Record 3 of Set 13 | meyungs
City not found. Skipping...
Processing Record 4 of Set 13 | batagay-alyta
Processing Record 5 of Set 13 | ayan
Processing Record 6 of Set 13 | wewak
Processing Record 7 of Set 13 | troitskoye
Processing Record 8 of Set 13 | arilje
Processing Record 9 of Set 13 | mitsamiouli
Processing Record 10 of Set 13 | aquiraz
Processing Record 11 of Set 13 | revelstoke
Processing Record 12 of Set 13 | saint-pierre
Processing Record 13 of Set 13 | bhainsdehi
Processing Record 14 of Set 13 | valenca
Processing Record 15 of Set 13 | sept-iles
Processing Record 16 of Set 13 | espita
-----------------------------
Data Retrieval Complete
-----------------------------

In [8]:
len(city_data)

570

In [9]:
# Convert array of JSONs into Pandas DataFrame
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description,Rain (inches),Snow (inches)
0,korla,41.7597,86.1469,85.05,18,5,13.69,CN,clear sky,0.00,0
1,jamestown,42.0970,-79.2353,77.29,67,75,5.99,US,broken clouds,0.00,0
2,airai,-8.9266,125.4092,61.07,62,52,3.69,TL,broken clouds,0.00,0
3,fort nelson,58.8053,-122.7002,71.62,43,43,2.66,CA,scattered clouds,0.00,0
4,victoria,22.2855,114.1577,88.97,90,98,1.01,HK,overcast clouds,0.00,0
5,fayaoue,-20.6500,166.5333,71.29,60,0,18.61,NC,clear sky,0.00,0
6,sechura,-5.5569,-80.8222,72.03,70,10,18.25,PE,clear sky,0.00,0
7,puerto ayora,-0.7393,-90.3518,73.08,74,10,11.54,EC,clear sky,0.00,0
8,barrow,71.2906,-156.7887,44.62,84,90,17.27,US,mist,0.00,0
9,panlaitan,12.1191,119.8486,83.19,83,100,19.33,PH,moderate rain,1.22,0

In [10]:
new_column_order = sorted(city_data_df.columns.tolist())
city_data_df = city_data_df[new_column_order]
city_data_df

,City,Cloudiness,Country,Current Description,Humidity,Lat,Lng,Max Temp,Rain (inches),Snow (inches),Wind Speed
0,korla,5,CN,clear sky,18,41.7597,86.1469,85.05,0.0,0,13.69
1,jamestown,75,US,broken clouds,67,42.0970,-79.2353,77.29,0.0,0,5.99
2,airai,52,TL,broken clouds,62,-8.9266,125.4092,61.07,0.0,0,3.69
3,fort nelson,43,CA,scattered clouds,43,58.8053,-122.7002,71.62,0.0,0,2.66
4,victoria,98,HK,overcast clouds,90,22.2855,114.1577,88.97,0.0,0,1.01
...,...,...,...,...,...,...,...,...,...,...,...
565,saint-pierre,75,RE,broken clouds,83,-21.3393,55.4781,67.68,0.0,0,16.11
566,bhainsdehi,100,IN,overcast clouds,89,21.6467,77.6325,70.29,0.0,0,8.28
567,valenca,28,BR,scattered clouds,93,-13.3703,-39.0731,69.26,0.0,0,1.50
568,sept-iles,62,CA,broken clouds,80,50.2001,-66.3821,59.72,0.0,0,11.10
569,espita,86,MX,overcast clouds,46,21.0167,-88.3167,91.31,0.0,0,8.01

In [11]:
city_data_df

,City,Cloudiness,Country,Current Description,Humidity,Lat,Lng,Max Temp,Rain (inches),Snow (inches),Wind Speed
0,korla,5,CN,clear sky,18,41.7597,86.1469,85.05,0.0,0,13.69
1,jamestown,75,US,broken clouds,67,42.0970,-79.2353,77.29,0.0,0,5.99
2,airai,52,TL,broken clouds,62,-8.9266,125.4092,61.07,0.0,0,3.69
3,fort nelson,43,CA,scattered clouds,43,58.8053,-122.7002,71.62,0.0,0,2.66
4,victoria,98,HK,overcast clouds,90,22.2855,114.1577,88.97,0.0,0,1.01
...,...,...,...,...,...,...,...,...,...,...,...
565,saint-pierre,75,RE,broken clouds,83,-21.3393,55.4781,67.68,0.0,0,16.11
566,bhainsdehi,100,IN,overcast clouds,89,21.6467,77.6325,70.29,0.0,0,8.28
567,valenca,28,BR,scattered clouds,93,-13.3703,-39.0731,69.26,0.0,0,1.50
568,sept-iles,62,CA,broken clouds,80,50.2001,-66.3821,59.72,0.0,0,11.10
569,espita,86,MX,overcast clouds,46,21.0167,-88.3167,91.31,0.0,0,8.01

In [12]:
city_data_df.dtypes

City                    object
Cloudiness               int64
Country                 object
Current Description     object
Humidity                 int64
Lat                    float64
Lng                    float64
Max Temp               float64
Rain (inches)          float64
Snow (inches)            int64
Wind Speed             float64
dtype: object

In [14]:
raining_cities = city_data_df.loc[city_data_df["Rain (inches)"] > 0]
raining_cities.head()

,City,Cloudiness,Country,Current Description,Humidity,Lat,Lng,Max Temp,Rain (inches),Snow (inches),Wind Speed
9,panlaitan,100,PH,moderate rain,83,12.1191,119.8486,83.19,1.22,0,19.33
22,faanui,25,PF,light rain,74,-16.4833,-151.7500,78.15,0.10,0,7.72
30,sitka,75,US,light rain,82,57.0531,-135.3300,58.89,0.25,0,0.00
33,bubaque,97,GW,light rain,82,11.2833,-15.8333,79.88,0.71,0,8.41
36,tautira,87,PF,light rain,73,-17.7333,-149.1500,82.00,0.27,0,10.94

In [15]:
snowing_cities = city_data_df.loc[city_data_df["Snow (inches)"] > 0]
snowing_cities.head()

Empty DataFrame
Columns: [City, Cloudiness, Country, Current Description, Humidity, Lat, Lng, Max Temp, Rain (inches), Snow (inches), Wind Speed]
Index: []

In [16]:
#Create The Output file csv

output_data_file = "data/WeatherPy_Database.csv"
city_data_df.to_csv(output_data_file, index_label = "City_ID")